### ISSUE TITLE
Provide a way to search for WooCommerce products

### ISSUE THREAD

**Issue by philcable** [washingtonstateuniversity/wsupress.wsu.edu#16]
There is an extension for this, so that could be an option.

**Comment by philcable** [comment]
The extension mentioned above is at https://docs.woocommerce.com/document/woocommerce-product-search/ and is a paid product, so building our own solution might be the option to go for.

**Comment by jeremyfelt** [comment]
A first option may be to use a search shortcode that's restricted to the WooCommerce product post type. It wouldn't be anything fancy, but could be placed wherever and would do the trick.

In the future we can probably take advantage of Elasticsearch and do our own search as you type.

**Comment by philcable** [comment]
👍  Working on a shortcode now!
