### ISSUE TITLE
Covers cropped when searching for books from blog sidebar

### ISSUE THREAD

**Issue by jeremyfelt** [washingtonstateuniversity/wsupress.wsu.edu#34]
![image001](https://cloud.githubusercontent.com/assets/286171/26224218/38caddec-3bd6-11e7-8227-9339f42471f6.jpg)

**Comment by jbickelhaupt** [comment]
This seems to only appear when searching from the blog sidebar (News).

**Comment by philcable** [comment]
We'll probably need to override the `/articles/post.php` file from the parent theme to fix this - see https://github.com/washingtonstateuniversity/WSUWP-spine-parent-theme/blob/master/articles/post.php#L43

**Comment by philcable** [comment]
And @jbickelhaupt is right, this is specific to the default search results template. It also happens in any browser :)
