### ISSUE TITLE
overlapping visual elements

### ISSUE THREAD

**Issue by edwardsala** [washingtonstateuniversity/wsupress.wsu.edu#39]
In Firefox. See screenshot below.

![shop_by_category___wsu_press_stage_site___washington_state_university](https://cloud.githubusercontent.com/assets/28792997/26226018/d439d0a0-3bde-11e7-844f-6f31d6022218.png)

**Comment by jbickelhaupt** [comment]
Fixed after some small style adjustments.

![image](https://cloud.githubusercontent.com/assets/6163495/26269590/599e9890-3caa-11e7-90a7-23f7e3e31f03.png)
