### ISSUE TITLE
Mobile shopping cart not rendering properly

### ISSUE THREAD

**Issue by edwardsala** [washingtonstateuniversity/wsupress.wsu.edu#41]
There are a number of layout issues on iPhone. Here's a screenshot of the top of the checkout page.

![file may 18 4 14 39 pm](https://cloud.githubusercontent.com/assets/28792997/26227107/31cda3a8-3be5-11e7-8a66-a4b6926d4e97.png)

**Comment by jbickelhaupt** [comment]
@edwardsala: I think I have this fixed now. Please confirm before I close this issue. Thanks!

**Comment by edwardsala** [comment]
Looks great!
