### ISSUE TITLE
On Mobile device: shopping cart caching SOME but not all field info

### ISSUE THREAD

**Issue by edwardsala** [washingtonstateuniversity/wsupress.wsu.edu#42]
On the Billing Details page the form is caching Address, Town, State and Zip field data. Not a huge deal but when you're on a phone it's kind of a pain to have to delete the cached info before being able to enter new.

![file may 18 4 34 38 pm](https://cloud.githubusercontent.com/assets/28792997/26227524/f0fb2abe-3be7-11e7-89a9-164b2a907baf.png)

**Comment by jeremyfelt** [comment]
This may be the browser auto-filling data into commonly named fields.

**Comment by jbickelhaupt** [comment]
@edwardsala: I agree with @jeremyfelt. You should be able to turn off that behavior in Settings > Safari > AutoFill. I'm going to close this issue since it's more of a default behavior that the user has to personally go in and modify.
