### ISSUE TITLE
SHOP pages are not showing in books in two slots

### ISSUE THREAD

**Issue by edwardsala** [washingtonstateuniversity/wsupress.wsu.edu#44]
![products___wsu_press_stage_site___washington_state_university](https://cloud.githubusercontent.com/assets/28792997/26257349/250bb750-3c75-11e7-8278-3b3227f98d10.png)

Also, how do we get to the .../shop/page/1/ pages?

**Comment by jeremyfelt** [comment]
I updated the posts per page setting to 12 from 10 in the admin. This should account for how we have the rows displayed.

A similar view is available in category pages -https://stage.wsupress.wsu.edu/product-category/nature-environment/

https://stage.wsupress.wsu.edu/shop/ isn't accessible anywhere now. We may want to put an "All titles" or something in the navigation under "Browse books".

**Comment by edwardsala** [comment]
Thank you. I sent a note to Caryn asking her where she would like to put a link. I love GitHub! 👍

**Comment by jbickelhaupt** [comment]
I had kind of played around with an All Titles link before but had ended up removing any links for it. 

Tinkering in the WooCommerce settings, I found a way to (I think) replace all instances where you'd get directed to the unlinked Shop page. The link still will say "Return to Shop" but now takers users to the Shop by Category page.

If we're good with that, then we can leave the rest of the site nav the same and have people whittle down their searches by category upon leaving the previous page.

**Comment by jbickelhaupt** [comment]
@edwardsala Upon further discovery, it looks like it now redirects you to the Shop by Category page, but actually lists all titles underneath it. Not quite the same as going to the Shop by Category page through the Spine nav, but still an OK experience in my mind. What do you or the Press folks think?

**Comment by edwardsala** [comment]
Whittling down through the categories page is good but we definitely want to have a link to the .../shop/page/1/ pages so people can flip through the entire catalog. Can we do this?
