### ISSUE TITLE
Set up a "Join our Mail list" page

### ISSUE THREAD

**Issue by philcable** [washingtonstateuniversity/wsupress.wsu.edu#47]
Clint suggests a Gravity Form for collecting the following information.

* Name (required)
* Email
* Physical address

Using MailChimp to maintain the list is an eventual goal.

**Comment by jbickelhaupt** [comment]
Page made and linked to from the homepage and in the nav. Just need a Gravity Form inserted into the page.

**Comment by jbickelhaupt** [comment]
Clint says that the form is done on this page. It currently sends a submission to the WSU Press email address. Please test it out and let us know what kind of text you want for the thank you message that gets emailed.
