### ISSUE TITLE
Secondary Page Names

### ISSUE THREAD

**Issue by jbickelhaupt** [washingtonstateuniversity/wsupress.wsu.edu#59]
Secondary page names are not always being generated and displaying correctly. Seems to be WooCommerce pages, but I'd like to have News show up on its page and we need something to populate on the Events page.

@philcable: If you have time to discuss, I'd love a second opinion. :)

**Comment by philcable** [comment]
Fixed in https://github.com/washingtonstateuniversity/wsupress.wsu.edu/pull/65.
