### ISSUE TITLE
Headers on Browse Books sub pages

### ISSUE THREAD

**Issue by edwardsala** [washingtonstateuniversity/wsupress.wsu.edu#61]
We have some issues when navigating to the sub pages under Browse Books. See notes in screen shots.
![shop_by_category___wsu_press___washington_state_university](https://user-images.githubusercontent.com/28792997/26847656-bacc5ba0-4ab2-11e7-87f9-eabf438589b8.png)
![bestsellers___product_categories___wsu_press___washington_state_university](https://user-images.githubusercontent.com/28792997/26847772-1434f6ac-4ab3-11e7-88b0-3bdb5e889eca.png)

**Comment by jbickelhaupt** [comment]
Closing this as it's already referenced in issue #59. I think Shop by Category must work as part of the WooCommerce plugin settings.
