### ISSUE TITLE
Change text on button Select Options to Buy

### ISSUE THREAD

**Issue by edwardsala** [washingtonstateuniversity/wsupress.wsu.edu#62]
![forthcoming_releases___product_categories___wsu_press___washington_state_university](https://user-images.githubusercontent.com/28792997/26848217-81b26182-4ab4-11e7-955b-31881a82b55a.png)

**Comment by jbickelhaupt** [comment]
@edwardsala - during a design meeting this morning, it was suggested that we use something other than "buy" as the button text. It gives a false sense that the user is going to Add to Cart or begin purchasing the book. After seeing the new button in action, I'm inclined to agree with them.

How about changing it to Details, Info, More Info, or something else? It would be more indicative of what info they'll actually get when they click on it.

**Comment by edwardsala** [comment]
Can we hide the button?

**Comment by edwardsala** [comment]
I see your point. ”Details", please.

:)

Thanks,

fyi: Amazon doesn’t have a button on their book Search results pages.

![image](https://user-images.githubusercontent.com/28792997/27055582-c4c736e0-4f79-11e7-8459-9c2dde87fb64.png)

**Comment by jbickelhaupt** [comment]
LOL. That was brought up too in our design meeting too. But Allen obviously felt like there was more merit for keeping it in. Oh, well.

Thanks for understanding.

Jon

**Comment by edwardsala** [comment]
No worries. Caryn was on the fence about keeping it so it will probably make her happy. All's good.
