### ISSUE TITLE
Pop up window text change request

### ISSUE THREAD

**Issue by edwardsala** [washingtonstateuniversity/wsupress.wsu.edu#63]
When you click on "ADD TO CART" for a book that is not yet available can we change the text in the pop up?
![crown_jewel_wilderness___wsu_press___washington_state_university](https://user-images.githubusercontent.com/28792997/26848501-80d174b4-4ab5-11e7-8797-cffdffcbe799.png)

**Comment by philcable** [comment]
@edwardsala Would hiding the quantity selector and "Add to Cart" button up for options that are out of stock or not yet available be a viable solution here?

I'm more than a little disappointed that it doesn't function that way out of the box, honestly.

**Comment by edwardsala** [comment]
Yes. That would work as long as the "Out of stock" notation above the button is what triggers the behavior. Reason is we will have "Out of stock" products in other categories besides Forthcoming Releases.
