### ISSUE TITLE
Book "status" disappears on product page

### ISSUE THREAD

**Issue by edwardsala** [washingtonstateuniversity/wsupress.wsu.edu#64]
![crown_jewel_wilderness___wsu_press___washington_state_university](https://user-images.githubusercontent.com/28792997/26848802-90e294d6-4ab6-11e7-880d-fe6a1c79199f.png)

**Comment by philcable** [comment]
@edwardsala I don't find this behavior unexpected or problematic, myself. That information is format specific, so if no format is selected, it makes sense that it wouldn't show up.

If we're to modify this behavior (no promises), what would you prefer to see happen?

**Comment by edwardsala** [comment]
I believe we resolved this by hiding the quantity and ADD TO CART buttons on "out of stock" items. So this issue can be closed as far as I'm concerned.

**Comment by philcable** [comment]
Sounds good, I'll close it out.
