### ISSUE TITLE
WA sales tax changing on July 1

### ISSUE THREAD

**Issue by edwardsala** [washingtonstateuniversity/wsupress.wsu.edu#77]
Effective July 1, 2017, sales tax rates for several areas are changing. The rate table can be found at  [http://genreceivables.wsu.edu/salesTaxDest.html](http://genreceivables.wsu.edu/salesTaxDest.html)

If you have any questions regarding Sales Tax changes please contact Karen Breese in General Accounting at 335-2056.

Debbie Stellyes

**Comment by jeremyfelt** [comment]
We're good here. The lookups are done live through dor.wa.gov - https://github.com/washingtonstateuniversity/WSUWP-Extended-WooCommerce/blob/master/includes/sales-tax.php#L42
