### ISSUE TITLE
Cybersource E-commerce issue

### ISSUE THREAD

**Issue by edwardsala** [washingtonstateuniversity/wsupress.wsu.edu#78]
@jeremyfelt @clintyoung When Kerry is putting through the charges. Cybersource is authorizing the price of the book, shipping and tax but is only charging the price of the book and shipping, NOT tax. See Transaction Status Summary on the upper right of screenshot below. She can fix this in Cybersource but we need to fix it so she doesn't have to do this every time there is tax involved.  Thanks!

**Comment by jeremyfelt** [comment]
Ugh, that's annoying. I'll open an issue with ESG on Monday and see what's going on.

**Comment by edwardsala** [comment]
I believe this has been resolved so am closing. If you think otherwise feel free to reopen.

**Comment by edwardsala** [comment]
For some reason this issue has come back to haunt us. Woo is calculating the amount to charge correctly book cost, tax and shipping but is dropping the tax when sending the amount to Cybersource.

**Comment by jeremyfelt** [comment]
Sorry @edwardsala, I should have looked closer at the beginning. It looks like there is something off in how the total is sent in the capture request. Even when viewing a past order in the admin, the tax rate is shown but no tax is added to the order. I'm looking for what we're missing now.

(I've removed the original screenshot to hide the customer's info)

**Comment by jeremyfelt** [comment]
Notes for refrence:

```
| tax_lines            | [{"id":272,"rate_code":"US-WA-TAX-1","rate_id":984097,"label":"8.6% Sales Tax","co |
|                      | mpound":false,"tax_total":"0.00","shipping_tax_total":"0.00","meta_data":[]},{"id" |
|                      | :273,"rate_code":"shipping","rate_id":0,"label":"8.6% Sales Tax (Shipping)","compo |
|                      | und":false,"tax_total":"0.00","shipping_tax_total":"0.00","meta_data":[]}]
```

Tax rates are stored in the database, but the `tax_total` has not been stored as part of the data and the `total` does not reflect it either.

**Comment by jeremyfelt** [comment]
This is now (🙏) fixed and deployed to production. The default tax rate has also been changed to 10.4% for cases where the API does not respond properly. @edwardsala I'll follow up in an email with some instructions.
