### ISSUE TITLE
WordPress admin login error

### ISSUE THREAD

**Issue by edwardsala** [washingtonstateuniversity/wsupress.wsu.edu#91]
Note from Kerry:

_Hi Ed,
When I go to wsupress.wsu.edu/admin, it asks for my log-in information. Once I enter it, I get this:_
 
![image001](https://user-images.githubusercontent.com/28792997/34621641-cf9c73f0-f1fe-11e7-8309-f9a7216f89d7.jpg)

 
_If I then type wsupress.wsu.edu/admin into the address bar again, it takes me straight to the WordPress dashboard (it doesn’t ask me to log-in again)._

**Comment by jeremyfelt** [comment]
Strange.

I'm able to reproduce this when I'm logged out. I'll take a look at it soon. Happy to hear the next attempt works at least.

**Comment by jeremyfelt** [comment]
@edwardsala This is fixed in production now. :)
