### ISSUE TITLE
Book cover thumbnails not rendering properly

### ISSUE THREAD

**Issue by edwardsala** [washingtonstateuniversity/wsupress.wsu.edu#92]
On all pages except the home page the book cover thumbnails are not rendering properly. Screenshot below. Approximately half of the cover is missing top and bottom.

![forthcoming_releases___product_categories___wsu_press___washington_state_university](https://user-images.githubusercontent.com/28792997/36169042-ecb1cd76-10af-11e8-93b6-24879d00a166.jpg)

**Comment by jbickelhaupt** [comment]
Thanks, Ed. Actually have this up and am looking at it right now. Will try to get this fixed ASAP.

**Comment by edwardsala** [comment]
Thank you! I know that GitHub is your preferred method of communicating this type of issue.

Edward J. Sala
Assistant Executive Director, University Communications | ucomm.wsu.edu
Director, Washington State University Press | wsupress.wsu.edu
Washington State University | wsu.edu
509-335-8638

**Comment by philcable** [comment]
@edwardsala This is fixed! The latest update to WooCommerce moved the product image options to the Customizer, evidently without preserving the previous settings.
