### ISSUE TITLE
Search by author doesn't return book titles

### ISSUE THREAD

**Issue by edwardsala** [washingtonstateuniversity/wsupress.wsu.edu#97]
Other search terms work as expected

Try

Scheuerman

Trafzer

**Comment by jeremyfelt** [comment]
@edwardsala I tried searching both Scheuerman and Trafzer and each return books in the search results in addition to blog posts that mention them. The search itself is comprehensive and will include posts, pages, and products (books) in the results.

**Comment by edwardsala** [comment]
Hmmm...Thanks for the quick response. Did Scheuerman return _Harvest Heritage, Snake River Palouse, Finding Chief Kamiakin_,  and _River Song_?

**Comment by jeremyfelt** [comment]
Ahh, that's probably it. In _River Song_, Scheuerman is mentioned in the book description, which is definitely included as part of the search. In _Harvest Heritage_, Scheuerman is listed as the author, but their name doesn't appear in the description.

I'll take a look at how we can make sure actual author names are included in the text that is searched. 👍

**Comment by edwardsala** [comment]
Ping.

**Comment by jeremyfelt** [comment]
@edwardsala This should be resolved as of a few minutes ago via #98. Author names and book subtitles are automatically added to the content indexed for search.

"Scheuerman" brings up _Harvest Heritage_, _Snake River Palouse_, _Finding Chief Kamiakin_, and _River Song_ now.

There is an hour long cache on previous search results. So if you had tested any other search terms earlier today, there's a chance that those won't work for a few minutes.
